global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "alerta-cheias"

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    metrics_path: /metrics

  # FastAPI application metrics
  - job_name: "alerta-cheias-api"
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ["prometheus"]

  # Redis metrics (if redis_exporter is added)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:9113"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Node exporter (system metrics - if added)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    metrics_path: /metrics
